# -*- coding: utf-8 -*-
"""Language Engineering Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MTPpZmt855rwyQKDtxt7PuzUEIYzMRFG
"""

pip install nltk

pip install newspaper3k

from newspaper import Article
 import random
 import string 
 from sklearn.feature_extraction.text import TfidfVectorizer
 from sklearn.metrics.pairwise import cosine_similarity
 import nltk
 import numpy as np
 import warnings

warnings.filterwarnings('ignore')

nltk.download('punkt', quiet=True)
nltk.download('wordnet', quiet=True)

article = Article('https://www.who.int/health-topics/coronavirus#tab=tab_1')
article.download()
article.parse()
article.nlp()
corpus = article.text

print(corpus)

text = corpus 
sent_tokens = nltk.sent_tokenize(text)

print(sent_tokens)

remove_punct_dict = dict( (ord(punct),None) for punct in string.punctuation)

print(string.punctuation)
print(remove_punct_dict)

def LemNormalize(text):
  return nltk.word_tokenize(text.lower().translate(remove_punct_dict))

print (LemNormalize(text))

GREETING_INPUTS = ["hi","hello","hey","wassup"]
GREETING_RESPONSES = ["hello","hey","hey there","hi","what's good"]

def greeting(sentence):
  for word in sentence.split():
    if word.lower() in GREETING_INPUTS:
      return random.choice(GREETING_RESPONSES)

def response(user_response):

  #user_response = 'What is Coronavirus disease'
  user_response = user_response.lower()
  #print(user_response)

  robo_response = ''

  sent_tokens.append(user_response)
  #print(sent_tokens)

  TfidfVec = TfidfVectorizer(tokenizer = LemNormalize, stop_words='english')

  tfidf = TfidfVec.fit_transform(sent_tokens)
  #print(tfidf)

  vals = cosine_similarity(tfidf[-1],tfidf)
  #print(vals)

  idx = vals.argsort()[0][-2]

  flat = vals.flatten()

  flat.sort()

  score = flat[-2]

  #print(score)

  if(score == 0):
    robo_response = robo_response+"I apologize, I don't understand."
  else:
    robo_response = robo_response+sent_tokens[idx] 
  
  #print(robo_response)
  
  sent_tokens.remove(user_response)   

  return robo_response

flag = True 
print("I will answer your queries about Coronavirus disease if you want to exit type Bye!")
while(flag == True):
  user_response = input()
  user_response = user_response.lower()
  if (user_response != 'bye'):
    if (user_response == 'thanks' or user_response == 'thank you'):
      flag = False
      print("you are welcome")
    else:
      if(greeting(user_response) != None):
        print(greeting(user_response))
      else:
        print(response(user_response))
  else:
    flag = False
    print("Chat with you later")